# Generated by Django 4.1.2 on 2022-10-24 17:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(120)]
                    ),
                ),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=50)),
                ("car_model", models.CharField(max_length=50)),
                ("year", models.PositiveIntegerField()),
                ("location", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Available"),
                            ("B", "Booked"),
                            ("R", "Rented"),
                            ("D", "Damaged"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mysite.customer",
                    ),
                ),
            ],
        ),

    ]
